# Generated by Django 5.0 on 2023-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
