# Generated by Django 5.0 on 2023-12-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_server_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='dtype',
            new_name='type',
        ),
    ]
