# Generated by Django 5.0 on 2024-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_dtype_server_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='enabled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
