# Generated by Django 5.0 on 2025-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_execution_task_workflow_execution_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
