# Generated by Django 5.0 on 2025-04-07 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-started"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="updated",
            new_name="completed",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="created",
            new_name="started",
        ),
    ]
