# Generated by Django 5.0 on 2025-04-07 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_alter_task_options_rename_updated_task_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="inputs",
        ),
    ]
