# Generated by Django 5.0 on 2025-04-15 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_alter_server_options_task_user_task_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
