# Generated by Django 5.0 on 2025-04-15 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_server_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserServers",
        ),
    ]
