# Generated by Django 5.0 on 2025-04-15 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_userservers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userservers",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
