# Generated by Django 5.0 on 2025-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_alter_userservers_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="content",
            field=models.JSONField(null=True),
        ),
    ]
